# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.1-node-browsers
      - image: circleci/postgres:11.3

    working_directory: ~/repo
    steps:
      - checkout
      - run:
         name: Start Chrome Driver
         command: /usr/local/bin/chromedriver
         background: true

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run:
          command: npm install
          working_directory: assets
      - run: mix credo --strict
      - run: mix format --check-formatted
      - run:
          name: eslint
          command: ./node_modules/.bin/eslint --format=junit --output-file="../test-results/eslint/junit.xml" js/**/*.js
          working_directory: assets
      - run:
          name: build assets
          command: npm install && npm run build
          working_directory: assets
      - run: mix ecto.create
      - run: MIX_ENV=test mix coveralls.circle
      - store_test_results:
          path: test-results

  deploy_staging:
    docker:
      - image: circleci/elixir:1.9.1-node-browsers
      - image: circleci/postgres:11.3

    steps:
      - checkout
      - run:
          name: Deploy master to Staging
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING_APP_NAME.git master

  deploy_production:
    docker:
      - image: circleci/elixir:1.9.1-node-browsers
      - image: circleci/postgres:11.3

    steps:
      - checkout
      - run:
          name: Deploy Release to Production
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
