# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.8.1-node-browsers
      - image: circleci/postgres:11.3

    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run:
          command: npm install
          working_directory: assets
      - run: mix credo --strict
      - run: mix format --check-formatted
      - run:
          name: eslint
          command: ./node_modules/.bin/eslint --format=junit --output-file="test/eslint/junit.xml" js/**/*.js
          working_directory: assets
      - run:
          name: build assets
          command: node node_modules/webpack/bin/webpack.js --mode development
          working_directory: assets
      - run: mix ecto.create
      - run: MIX_ENV=test mix coveralls.circle
  deploy:
    docker:
      - image: circleci/elixir:1.6.4-node-browsers
      - image: circleci/postgres:9.4

    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
